@host=https://localhost:7031
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTgzZmJmZS1mNThhLTQ2YjAtYWMzMS1jMGI1MWVjMjU5M2MiLCJnaXZlbl9uYW1lIjoid2FsaWRzIiwiZmFtaWx5X25hbWUiOiJKb2huIiwianRpIjoiYmUzZTgwMGItNTA2ZC00MzBlLThjYmEtYWVhYWEyYzc3MDQ0IiwiZXhwIjoxNzMwMDY2OTkzLCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.zGtzPO--sN7V_YnZFz42doDJMcmdIjL2FJN0UCmpVlU

POST {{host}}/hosts/{{hostId}}/menu
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}