@host=https://localhost:7031

GET {{host}}/dinners/DinnersList
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNDhmOWU2Ni04OTk3LTQ2NmMtODA4MC1iZDE2MmI4ODE5YzEiLCJnaXZlbl9uYW1lIjoid2FsaWRzIiwiZmFtaWx5X25hbWUiOiJKb2huIiwianRpIjoiODNlODFhN2MtY2FjMi00NzdlLThlM2EtZDFiMzhjMmE2ZDE4IiwiZXhwIjoxNzI4Njc1Mjk0LCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.xRpRP_xQiJ6MWjaIzWvkNK6Cg4Gq5ENyfPps-msvWhU