@host=https://localhost:7031

POST {{host}}/auth/register 
Content-Type: application/json
 
 {
    "firstName":"walids",
    "lastName":"John",
    "email":"someone@yoyossa.com",
    "password":"Amiko1232!"
}